### ISSUE TITLE
AsyncAPI Importer - should default to application/json content type

### ISSUE THREAD

**Issue by 195858** [SolaceLabs/solace-tools-typescript#116]
**Describe the bug**
The importer validates the API spec and requires either a contentType being present on the message or a defaultContentType.
However neither of these are required by the Async API spec.

**To Reproduce**
1. command line
 ep-async-api-importer -fp ~/Downloads/CE_FREIGHTBOOKINGEVENTS.yaml
 Async APi file - https://gist.github.com/195858/0aa1a2ddc1bb6594785344f67657a9d5
2. configuration
CLI_TEST_SETUP_DOMAINS_FOR_APIS=false
CLI_ASSETS_APPLICATION_DOMAIN_ENFORCEMENT_POLICY=off
CLI_IMPORT_BROKER_TYPE=solace
A clear and concise description of what happens.
Error message
  "epAsyncApiError": {
    "baseName": "EpAsyncApiError",
    "internalMessage": "EP Async Api Message Error",
    "name": "_EpAsyncApiMessageError",
    "internalLogName": "_EpAsyncApiMessageDocument.determineContentType()",
    "internalModuleNName": "_EpAsyncApiMessageDocument",
    "internalStack": [
      "_EpAsyncApiMessageError: EP Async Api Message Error",
      "    at _EpAsyncApiMessageDocument.determineContentType (/Users/swenhelge/.nvm/versions/node/v18.16.0/lib/node_modules/@solace-labs/ep-async-api-importer/node_modules/@solace-labs/ep-asyncapi/dist/index.js:283:13)",
      "    at new _EpAsyncApiMessageDocument (/Users/swenhelge/.nvm/versions/node/v18.16.0/lib/node_modules/@solace-labs/ep-async-api-importer/node_modules/@solace-labs/ep-asyncapi/dist/index.js:325:29)",
      "    at EpAsyncApiChannelDocument.getAllChannelMessageDocuments (/Users/swenhelge/.nvm/versions/node/v18.16.0/lib/node_modules/@solace-labs/ep-async-api-importer/node_modules/@solace-labs/ep-asyncapi/dist/index.js:826:43)",
      "    at EpAsyncApiChannelDocument.createMessageDocument (/Users/swenhelge/.nvm/versions/node/v18.16.0/lib/node_modules/@solace-labs/ep-async-api-importer/node_modules/@solace-labs/ep-asyncapi/dist/index.js:837:40)",
      "    at new EpAsyncApiChannelDocument (/Users/swenhelge/.nvm/versions/node/v18.16.0/lib/node_modules/@solace-labs/ep-async-api-importer/node_modules/@solace-labs/ep-asyncapi/dist/index.js:771:43)",
      "    at _EpAsyncApiDocument.getEpAsyncApiChannelDocumentMap (/Users/swenhelge/.nvm/versions/node/v18.16.0/lib/node_modules/@solace-labs/ep-async-api-importer/node_modules/@solace-labs/ep-asyncapi/dist/index.js:1423:41)",
      "    at _EpAsyncApiDocument.validate (/Users/swenhelge/.nvm/versions/node/v18.16.0/lib/node_modules/@solace-labs/ep-async-api-importer/node_modules/@solace-labs/ep-asyncapi/dist/index.js:1308:47)",
      "    at EpAsyncApiDocumentServiceClass.createFromFile (/Users/swenhelge/.nvm/versions/node/v18.16.0/lib/node_modules/@solace-labs/ep-async-api-importer/node_modules/@solace-labs/ep-asyncapi/dist/index.js:1514:26)",
      "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
      "    at async CliAsyncApiDocumentService.parse_and_validate (/Users/swenhelge/.nvm/versions/node/v18.16.0/lib/node_modules/@solace-labs/ep-async-api-importer/dist/cli.js:47822:36)"
    ],
    "details": {
      "issue": "contentType === undefined, neither message has a contentType nor api has a defaultContentType",
      "apiTitle": " Freight Booking Events",
      "apiChannel": "ce/sap/s4/beh/FreightBooking/BlockStatusChanged/v1",
      "apiMessage": "sap.s4.beh.FreightBooking.BlockStatusChanged.v1",

**Expected behavior**
The Async API importer should assume application/json content when the content type is not explicitly set.

**Log files**
If applicable, add log file(s) to help troubleshoot the problem.

**Additional context**

**Comment by TamimiGitHub** [comment]
Thanks for opening this issues. I recall we added the requirement on content type due to the event portal requirement for a content type. However, the importer could be modified to include a default content type if not provided by the spec file
