### ISSUE TITLE
Extracting Application Domain Name from the spec in the info block

### ISSUE THREAD

**Issue by TamimiGitHub** [SolaceLabs/solace-tools-typescript#17]
## Current Behaviour

The current behaviour of the importer extracts the application domain name from the `x-ep-application-domain-name` extension that is found in the root level of the spec. 

## Expected behaviour
`x-ep-application-domain-name` is in the `info` block

## Importer version 
0.52.0

**Comment by ricardojosegomezulmke** [comment]
released in version 0.52.2

**Comment by TamimiGitHub** [comment]
Commit for reference https://github.com/SolaceLabs/solace-tools-typescript/commit/4ee2da363ffbd6c50ff79a6a3c03a899d588d895
