### ISSUE TITLE
Handeling issues with shared event in TEST_MODE

### ISSUE THREAD

**Issue by TamimiGitHub** [SolaceLabs/solace-tools-typescript#29]
## Current Issue
As of right now, TEST_MODE does not handle issues with shared events. 

## Proposed Solution
After consensus on how to handle issues with shared event, we need to incorporate that in TEST_MODE checks to avoid failure on RELEASE_MODE importing after a successful TEST_MODE import

**Comment by ricardojosegomezulmke** [comment]
can you please provide info/data to reproduce?

**Comment by TamimiGitHub** [comment]
This is an example on how the importer could fail on shared event
https://github.com/jessemenning/checkInEngine/actions/runs/4077337814/jobs/7026250863

**Comment by TamimiGitHub** [comment]
Closing in favour of #36
